# Generated by Django 5.2.3 on 2025-12-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('hoursRequested', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('professorComent', models.TextField(blank=True, null=True)),
                ('projectId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcu_system_app.project')),
                ('statusId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcu_system_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('filePath', models.FileField(upload_to='uploads/')),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcu_system_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('projectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcu_system_app.project')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcu_system_app.role')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='userId_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='tcu_system_app.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='userId_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcu_system_app.user'),
        ),
    ]
