# Generated by Django 5.2.3 on 2025-12-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcu_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='NA', max_length=50, unique=True),
        ),
    ]
