# Generated by Django 5.2.3 on 2025-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcu_system_app', '0002_alter_status_options_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='revisionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
