# Generated by Django 5.2.3 on 2025-12-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcu_system_app', '0004_alter_request_revisiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='revisionDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
