# Generated by Django 5.2.3 on 2025-12-09 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcu_system_app', '0005_alter_request_revisiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='revisionDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
